


target 'ReindeerDemo' do
  use_frameworks!
  platform :ios, '9.0'
  pod 'Reindeers', git: 'https://github.com/onmyway133/Reindeers'

end

target 'ReindeerMacApp' do
  use_frameworks!
  platform :osx, '10.12'
  pod 'Reindeers', git: 'https://github.com/onmyway133/Reindeers'
end
